Repository Griffollion/TMS55TEST, pull requests merged in 2021-07, with the labels that each got.

#101 Vlad kozlovski home work 5
  Vlad_Kozlovski/solutions/homeWork5/index.html
  Vlad_Kozlovski/solutions/homeWork5/script.js
  homeworks/homeWork4.md
  homeworks/homeWork5.md
  materials/lesson4/TMS-Basic-JS.lesson-4.pdf
  materials/lesson4/useful-links.md
  materials/lesson5/TMS-Basic-JS.lesson-5.pdf
  materials/lesson5/useful-links.md
Labels: ready for merge

#111 Vlad kozlovski home work 6
  Vlad_Kozlovski/solutions/homeWork6/index.html
  Vlad_Kozlovski/solutions/homeWork6/script.js
  homeworks/homeWork6.md
  materials/lesson6/TMS-Basic-JS.lesson-6.pdf
  materials/lesson6/classWork/app.js
  materials/lesson6/classWork/index.html
  materials/lesson6/useful-links.md
Labels: ready for merge

#109 Rekun Olga homework6
  homeworks/homeWork6.md
  materials/lesson6/TMS-Basic-JS.lesson-6.pdf
  materials/lesson6/classWork/app.js
  materials/lesson6/classWork/index.html
  materials/lesson6/useful-links.md
  solutions/homework6/app.js
  solutions/homework6/index.html
Labels: ready for merge

#112 Alex_Karseka-homeWork6
  solutions/homeWork6/add.js
  solutions/homeWork6/index.html
Labels: ready for merge

#96 Fourth homeWork of Harbatsevich
  solutions/homeWork4/app.js
  solutions/homeWork4/index.html
Labels: need to fix

#114 Yana varsak home work 6
  homeworks/homeWork6.md
  materials/lesson6/TMS-Basic-JS.lesson-6.pdf
  materials/lesson6/classWork/app.js
  materials/lesson6/classWork/index.html
  materials/lesson6/useful-links.md
  solutions/app.js
  solutions/homeWork6/app.js
  solutions/homeWork6/index.html
Labels: need to fix

#116 Kolay_Tolkun. Finish homeWork_6 not full
  homeworks/homeWork6.md
  solutions/homework6/app.js
  solutions/homework6/index.html
Labels: ready for review

#122 Dmitry kosenko homework7
  homeworks/homeWork7.md
  materials/lesson7/classWork/TMS-Basic-JS.lesson-7.pdf
  materials/lesson7/classWork/app.js
  materials/lesson7/classWork/index.html
  materials/lesson7/useful-links.md
  solutions/homework-7/app.js
  solutions/homework-7/index.html
Labels: ready for review

#120 Rekun olga homework7
  homeworks/homeWork7.md
  materials/lesson7/classWork/TMS-Basic-JS.lesson-7.pdf
  materials/lesson7/classWork/app.js
  materials/lesson7/classWork/index.html
  materials/lesson7/useful-links.md
  solutions/homework7/app.js
  solutions/homework7/index.html
Labels: ready for merge

#123 Alex_Karseka-homeWork7
  solutions/homeWork7/add.js
  solutions/homeWork7/index.html
Labels: ready for review

#125 Yana varsak home work 7 level up
  homeworks/homeWork7.md
  materials/lesson7/classWork/TMS-Basic-JS.lesson-7.pdf
  materials/lesson7/classWork/app.js
  materials/lesson7/classWork/index.html
  materials/lesson7/useful-links.md
  solutions/homeWork7/app.js
  solutions/homeWork7/index.html
Labels: ready for merge

#124 Vlad kozlovski home mork 7
  Vlad_Kozlovski/solutions/homeWork7/index.html
  Vlad_Kozlovski/solutions/homeWork7/script.js
  homeworks/homeWork7.md
  materials/lesson7/classWork/TMS-Basic-JS.lesson-7.pdf
  materials/lesson7/classWork/app.js
  materials/lesson7/classWork/index.html
  materials/lesson7/useful-links.md
Labels: ready for merge

#121 Dmitry kosenko homework6
  solutions/homework-6/app.js
Labels: ready for review

#130 Rekun Olga homework8
  homeworks/homeWork8.md
  materials/lesson8/classWork/app.js
  materials/lesson8/classWork/index.html
  materials/lesson8/classWork/styles.css
  materials/lesson8/useful-links.md
  solutions/homework8/app.js
  solutions/homework8/img/opel.jpg
  solutions/homework8/index.html
  solutions/homework8/style.css
Labels: ready for merge

#133 Trubko alexey homework8
  homeworks/homeWork3.md
  homeworks/homeWork4.md
  homeworks/homeWork5.md
  homeworks/homeWork6.md
  homeworks/homeWork7.md
  homeworks/homeWork8.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  materials/lesson4/TMS-Basic-JS.lesson-4.pdf
  materials/lesson4/useful-links.md
  materials/lesson5/TMS-Basic-JS.lesson-5.pdf
  materials/lesson5/useful-links.md
  materials/lesson6/TMS-Basic-JS.lesson-6.pdf
  materials/lesson6/classWork/app.js
  materials/lesson6/classWork/index.html
  materials/lesson6/useful-links.md
  materials/lesson7/classWork/TMS-Basic-JS.lesson-7.pdf
  materials/lesson7/classWork/app.js
  materials/lesson7/classWork/index.html
  materials/lesson7/useful-links.md
  materials/lesson8/classWork/app.js
  materials/lesson8/classWork/index.html
  materials/lesson8/classWork/styles.css
  materials/lesson8/useful-links.md
  solutions/homework8/app.js
  solutions/homework8/index.html
  solutions/homework8/style.css
Labels: need to fix

#132 Alex_karseka-homeWork8
  solutions/homeWork8/add.js
  solutions/homeWork8/index.html
  solutions/homeWork8/style.css
Labels: ready for review

#128 Dmitry kosenko homework8
  homeworks/homeWork8.md
  materials/lesson8/classWork/app.js
  materials/lesson8/classWork/index.html
  materials/lesson8/classWork/styles.css
  materials/lesson8/useful-links.md
  solutions/homework-8/app-2.js
  solutions/homework-8/app.js
  solutions/homework-8/index.html
  solutions/homework-8/style-2.css
  solutions/homework-8/style.css
Labels: ready for review

#137 Artyn artem hm4
  solution/homework-3/app.js
  solution/homework-3/index.html
  solution/homework-4/app.js
  solution/homework-4/index.html
Labels: ready for review

#135 Добавила 42 задачу с конструкторами
  solutions/homework7/app.js
Labels: ready for merge

#140 Alex_Karseka-homeWork9
  solutions/homeWork9/app.js
  solutions/homeWork9/index.html
  solutions/homeWork9/styles.css
Labels: ready for review

#141 Rekun Olga homework9
  .vscode/settings.json
  homeworks/homeWork9.md
  materials/lesson9/TMS-Basic-JS.lesson-9.pdf
  materials/lesson9/classWork/app.js
  materials/lesson9/classWork/index.html
  materials/lesson9/classWork/styles.css
  materials/lesson9/useful-links.md
  solutions/homework9/app.js
  solutions/homework9/index.html
  solutions/homework9/style.css
Labels: ready for merge

#147 Dmitry kosenko homework10
  homeworks/homeWork10.md
  materials/lesson10/classWork/user_form/css/styles.css
  materials/lesson10/classWork/user_form/index.html
  materials/lesson10/classWork/user_form/js/app.js
  materials/lesson10/classWork/user_form/js/user-form.js
  materials/lesson10/classWork/user_form/js/validations.js
  materials/lesson10/classWork/user_form/libs/materialize/css/materialize.css
  materials/lesson10/classWork/user_form/libs/materialize/js/materialize.js
  materials/lesson10/useful-links.md
  solutions/homework-10/css/materialize.css
  solutions/homework-10/css/style.css
  solutions/homework-10/index.html
  solutions/homework-10/js/app.js
  solutions/homework-10/js/materialize.js
Labels: ready for review

#165 Rekun Olga homework12
  .vscode/settings.json
  homeworks/homeWork10.md
  homeworks/homeWork11.md
  homeworks/homeWork12.md
  materials/lesson10/classWork/user_form/css/styles.css
  materials/lesson10/classWork/user_form/index.html
  materials/lesson10/classWork/user_form/js/app.js
  materials/lesson10/classWork/user_form/js/user-form.js
  materials/lesson10/classWork/user_form/js/validations.js
  materials/lesson10/classWork/user_form/libs/materialize/css/materialize.css
  materials/lesson10/classWork/user_form/libs/materialize/js/materialize.js
  materials/lesson10/useful-links.md
  materials/lesson11/classWork/other/app.js
  materials/lesson11/classWork/other/index.html
  materials/lesson11/classWork/other/styles.css
  materials/lesson11/classWork/redirects/.vscode/settings.json
  materials/lesson11/classWork/redirects/index.html
  materials/lesson11/classWork/redirects/pages/sales/index.html
  materials/lesson11/classWork/redirects/src/css/styles.css
  materials/lesson11/classWork/redirects/src/js/app.js
  materials/lesson11/classWork/render_content/index.html
  materials/lesson11/classWork/render_content/src/css/styles.css
  materials/lesson11/classWork/render_content/src/js/app.js
  materials/lesson11/useful-links.md
  materials/lesson12/classWork/AJAX/.vscode/launch.json
  materials/lesson12/classWork/AJAX/.vscode/settings.json
  materials/lesson12/classWork/AJAX/index.html
  materials/lesson12/classWork/AJAX/src/css/styles.css
  materials/lesson12/classWork/AJAX/src/data/users.json
  materials/lesson12/classWork/AJAX/src/js/app.js
  materials/lesson12/useful-links.md
  solutions/homework12/index.html
  solutions/homework12/src/css/style.css
  solutions/homework12/src/data/movies.json
  solutions/homework12/src/js/app.js
Labels: ready for merge

#157 Dmitry kosenko homework11
  .vscode/settings.json
  homeworks/homeWork11.md
  homeworks/homeWork12.md
  materials/lesson11/classWork/other/app.js
  materials/lesson11/classWork/other/index.html
  materials/lesson11/classWork/other/styles.css
  materials/lesson11/classWork/redirects/.vscode/settings.json
  materials/lesson11/classWork/redirects/index.html
  materials/lesson11/classWork/redirects/pages/sales/index.html
  materials/lesson11/classWork/redirects/src/css/styles.css
  materials/lesson11/classWork/redirects/src/js/app.js
  materials/lesson11/classWork/render_content/index.html
  materials/lesson11/classWork/render_content/src/css/styles.css
  materials/lesson11/classWork/render_content/src/js/app.js
  materials/lesson11/useful-links.md
  materials/lesson12/classWork/AJAX/.vscode/launch.json
  materials/lesson12/classWork/AJAX/.vscode/settings.json
  materials/lesson12/classWork/AJAX/index.html
  materials/lesson12/classWork/AJAX/src/css/styles.css
  materials/lesson12/classWork/AJAX/src/data/users.json
  materials/lesson12/classWork/AJAX/src/js/app.js
  materials/lesson12/useful-links.md
  solutions/homework-11/render_content/index.html
  solutions/homework-11/render_content/src/css/styles.css
  solutions/homework-11/render_content/src/js/app.js
  solutions/homework-11/render_content/src/movies.json
Labels: ready for review
