Repository Griffollion/TMS55TEST, pull requests merged in 2021-06, with the labels that each got.

#11 Andrey
  Kutsko_Andrey.md
Labels: ready for merge

#12 add artynskij file
  artynskij_artem.md
Labels: ready for merge

#16 Alex karseka homework1 variable
  homeWork1.md
  homeworks/homeWork1.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  solutions/homework1.md
Labels: ready for merge

#20 Denis filipovich home work 1 git
  Denis_Filipovich.md
  homeWork1.md
  homeworks/homeWork1.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  solucions/homeWork1.md
Labels: ready for merge

#31 my expectations from js
  homeWork1.md
  homeworks/homeWork1.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  rekun_olga.md
  solutions/homework1_rekun.md
Labels: ready for merge

#30 Karina romashko home work 1 git
  homeWork1.md
  homeworks/homeWork1.md
  index.html
  karina.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  solutions/homeWork1.md
Labels: ready for merge

#29 Artsiom harbatsevich home work 1 git
  artsiom_harbatsevich.md
  homeWork1.md
  homeworks/homeWork1.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  solutions/homework1.md
Labels: ready for merge

#32 Matvei egorov homework 1 git
  Egorov.md
  homeWork1.md
  homeworks/homeWork1.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  solucions/homework1.md
Labels: ready for merge

#35 Kolay_Tolkun. Finish homeWork_1
  console-errore-code.docx
  solutions/homework1.md
Labels: ready for merge

#42 Karina romashko home work 2 js
  homeworks/homeWork2.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homeWork2/app.js
  solutions/homeWork2/index.html
Labels: ready for merge

#43 Dmitry Kosenko homework 2
  homeworks/homeWork1.md
  homeworks/homeWork2.md
  materials/lesson1/lesson1.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework-1.md
  solutions/homework-2/app.js
  solutions/homework-2/index.html
Labels: ready for review

#44 Homework2
  solucions/homework2/index.html
Labels: ready for review

#48 Alex karseka homework2
  homeworks/homeWork1.md
  homeworks/homeWork2.md
  materials/lesson1/lesson1.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework2/add.js
  solutions/homework2/index.html
Labels: ready for review

#49 Kutsko Andrey homework2
  homeworks/homeWork2.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework2/app.js
  solutions/homework2/index.html
Labels: ready for merge

#51 Vlad kozlovski home work1
  Vlad_Kozlovski/solutions/homeWork2/index.html
  Vlad_Kozlovski/solutions/homeWork2/script.js
  Vlad_Kozlovski/solutions/homework1.md
  homeWork1.md
  homeworks/homeWork1.md
  homeworks/homeWork2.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
Labels: ready for merge

#52 Rekun olga homework2 variable
  homeworks/homeWork2.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework2/apps.js
  solutions/homework2/index.html
Labels: ready for merge

#50 Kolay tolkun home work 2 git
  homeworks/homeWork2.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework2/app.js
  solutions/homework2/index.html
Labels: ready for review

#57 Тёма победоносец домашка 2
  solution/homework-2/app.js
  solution/homework-2/index.html
  solution/homework1.md
Labels: ready for review

#59 Trubko alexey homework2
  homeworks/homeWork1.md
  homeworks/homeWork2.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework1.md
  solutions/homework2/app.js
  solutions/homework2/index.html
Labels: ready for review

#58 Valerya zen home work2 v
  homeWork1.md
  homeworks/homeWork1.md
  homeworks/homeWork2.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework1.md
  solutions/homework2/app.js
  solutions/homework2/index.html
Labels: ready for review

#56 Artsiom harbatsevich home work2
  homeworks/homeWork2.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  solutions/homework2/app.js
  solutions/homework2/index.html
Labels: ready for review

#70 Kolay tolkun home work 3 git
  homeworks/homeWork3.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  solutions/homework3/app.js
  solutions/homework3/index.html
Labels: ready for review

#72 Alex karseka home work3
  homeworks/homeWork3.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  solutions/homeWork3/add.js
  solutions/homeWork3/index.html
Labels: need to fix

#27 Dasha finished Hw1
  homeWork1.md
  homeworks/homeWork1.md
  homeworks/homeWork2.md
  homeworks/homeWork3.md
  homeworks/homeWork4.md
  materials/lesson1/TMS-Basic-JS.lesson-1.pdf
  materials/lesson1/lesson1.md
  materials/lesson2/TMS-Basic-JS.lesson-2.pdf
  materials/lesson2/cool-sites.md
  materials/lesson2/useful-links.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  materials/lesson4/TMS-Basic-JS.lesson-4.pdf
  materials/lesson4/useful-links.md
  solutions/homework1.md
Labels: ready for review

#69 Dmitry kosenko homework3
  homeworks/homeWork3.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  solutions/homework-3/app.js
  solutions/homework-3/index.html
Labels: ready for review

#86 Rekun olga homework 3
  homeworks/homeWork3.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  solutions/homework3/apps.js
  solutions/homework3/index.html
Labels: ready for merge

#68 Vlad kozlovski home work3
  .vscode/settings.json
  Vlad_Kozlovski/solutions/homeWork3/index.html
  Vlad_Kozlovski/solutions/homeWork3/script.js
  homeworks/homeWork3.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
Labels: ready for merge

#89 Alex karseka home work4
  Alex_Karseka.md
  homeworks/homeWork4.md
  materials/lesson4/TMS-Basic-JS.lesson-4.pdf
  materials/lesson4/useful-links.md
  solutions/homeWork3/add.js
  solutions/homeWork4/add.js
  solutions/homeWork4/index.html
  solutions/homework1.md
  solutions/homework2/add.js
  solutions/homework2/index.html
Labels: ready for review

#93 third homeWork of Harbatsevich
  solutions/homeWork3/app.js
  solutions/homeWork3/index.html
Labels: ready for review

#87 Kolay tolkun home work 4 git
  homeworks/homeWork4.md
  materials/lesson4/TMS-Basic-JS.lesson-4.pdf
  materials/lesson4/useful-links.md
  solutions/homework3/app.js
Labels: ready for review

#99 Alex_Karseka-homeWork5
  solutions/homeWork5/add.js
  solutions/homeWork5/index.html
Labels: ready for review

#102 Yana varsak home work 5 basic
  homeworks/homeWork3.md
  homeworks/homeWork4.md
  homeworks/homeWork5.md
  materials/lesson3/TMS-Basic-JS.lesson-3.pdf
  materials/lesson3/classesCode/app.js
  materials/lesson3/classesCode/index.html
  materials/lesson3/useful-links.md
  materials/lesson4/TMS-Basic-JS.lesson-4.pdf
  materials/lesson4/useful-links.md
  materials/lesson5/TMS-Basic-JS.lesson-5.pdf
  materials/lesson5/useful-links.md
  solutions/app.js
  solutions/index.html
Labels: ready for merge

#100 Rekun olga homewrok5
  homeworks/homeWork5.md
  materials/lesson5/TMS-Basic-JS.lesson-5.pdf
  materials/lesson5/useful-links.md
  solutions/homework5/app.js
  solutions/homework5/index.html
Labels: ready for merge
